#!/bin/bash
if [ $# -eq 0 ]; then
    ./"${0##*/}" --help
fi

for i in "$@"
do
case $i in
    -i|--install)
	plasmapkg2 -i package
    ;;
    -u|--update)
	git pull
    	plasmapkg2 -u package
    ;;
    -r|--remove)
	plasmapkg2 -r package
    ;;
    -g|--global-install)
    #cmake; make;
    supkg=$(which sudo 2>/dev/null)
    if [ $(id -u) -eq 0 ] || [ $supkg ]; then
      $supkg make install
    else
      echo "Sorry, I could not find sudo package. You have to manually install: start 'make install' with apropriate rights."
    fi
    ;;
    *)
	echo "Usage:"
	echo "-i|--install     :     (local) installation"
	echo "-u|--update      :     update (local) installation"
	echo "-r|--remove      :     remove (local) installation"
	echo ""
    ;;
esac
done;
